### ISSUE TITLE
Не работает Webpack DevServer

### ISSUE THREAD

**Issue by ivanartamonov** [ivanartamonov/otus-weather#2]
### Короткое описание
Изначально установил Browsersync, с ним все работает. Потом решил перейти на WebPack DevServer, удалил из конфига плагин browsersync, вместо него прописал devServer как в [документации](https://webpack.js.org/configuration/dev-server/), пробую запустить `npx webpack serve --open --mode development`, сервер стартует, но сайт не работает, так как он не может найти файлы. Ошибки в консоль не пишет.

Спойлер: проблема в том, что я хочу, чтоб у меня была папка public, где будет index.html, а в ней уже папка dist, где будет весь остальной выхлоп (css, js, images etc.). И сервер смотрит в public/dist, вместо public. Я знаю как поменять, но тогда не работает production сборка... Детали ниже.

### Детали

**WebPack Config**
```
const path = require('path');
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");

const mode = process.env.NODE_ENV;

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'public/dist'),
    filename: 'bundle.js',
    clean: true
  },
  target: ['web', 'es5'],
  devtool: mode === 'production' ? 'source-map' : 'inline-source-map',
  devServer: {
    compress: true,
    port: 9000,
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: path.resolve(__dirname, "public/index.html"),
      template: path.resolve(__dirname, "src/index.html")
    }),
    new MiniCssExtractPlugin()
  ],
  optimization: {
    minimizer: [
      `...`,
      new CssMinimizerPlugin(),
    ],
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      },
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, "css-loader"],
      },
      {
        test: /\.(png|jpg|jpeg|svg|gif)$/i,
        type: "asset/resource",
        generator: {
          filename: "images/[hash][ext]"
        }
      },
      {
        test: /\.html$/i,
        loader: "html-loader",
      },
    ]
  }
};
```

Запускаю командой  `npx webpack serve --open --mode development`

В консоли выводит:
```
(base) ivanartamonov@MacBook-Pro-Ivan:~/WebProjects/js-basic/weather$ npx webpack serve --open --mode development
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.5.136:9000/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:9000/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/ivanartamonov/WebProjects/js-basic/weather/public' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
asset bundle.js 600 KiB [emitted] (name: main)
asset main.css 638 bytes [emitted] (name: main)
asset ../index.html 463 bytes [emitted]
Entrypoint main 600 KiB = main.css 638 bytes bundle.js 600 KiB
runtime modules 43.1 KiB 22 modules
orphan modules 3.57 KiB [orphan] 3 modules
cacheable modules 167 KiB (javascript) 39 bytes (css/mini-extract)
  modules by path ./node_modules/ 167 KiB
    modules by path ./node_modules/webpack-dev-server/client/ 56.8 KiB 12 modules
    modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
    modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
    modules by path ./node_modules/mini-css-extract-plugin/dist/hmr/*.js 5.97 KiB 2 modules
    ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
    ./node_modules/events/events.js 14.5 KiB [built] [code generated]
  modules by path ./assets/styles/*.css 326 bytes (javascript) 39 bytes (css/mini-extract)
    ./assets/styles/main.css 326 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./assets/styles/main.css 39 bytes [built] [code generated]
  ./src/index.js 109 bytes [built] [code generated]
webpack 5.70.0 compiled successfully in 2501 ms
```

Если изменять файлы, то в консоли добавляется инфа, что такой-то такой-то файл успешно обработан... Т.е. listener работает. Ошибок в консоли по-прежнему нет. 

В папке public/..., куда должен попадать выхлоп ничего не сохраняется. На лекции преподаватель говорил, что файлы и не должны появляться и это наоборот такая классная фича, что все в памяти и от этого очень быстро работает. У меня как будто он прекрасно все отслеживает и компилит в памяти, но браузер из этой памяти файлы не видит, если так можно выразиться.

**В браузере показывается следующее:**
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/7717669/160117467-72bf3c32-538a-4e4e-9780-1c67ade26603.png">

**Если перейти по адресу http://localhost:9000/webpack-dev-server:**
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/7717669/160117592-25d43a9b-3fff-4582-8abb-8ac03e6757cb.png">

Если тыкнуть в какой-то из файлов:
Например стили, то файл есть
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/7717669/160117825-f9d0b0c2-f7e2-4640-97bd-f75c6645dc0f.png">

**По адресу http://localhost:9000/index.html выдает такое:**
<img width="737" alt="image" src="https://user-images.githubusercontent.com/7717669/160120539-a93a5879-eb12-4978-ad6f-c42539998c7b.png">

Тут обращаем внимание, что путь к файлу index.html ведет на уровень выше "../". Получается, что dev-server запущен как бы в папке "public/dist", а должен работать из "public".

**Структура папок:**
<img width="352" alt="image" src="https://user-images.githubusercontent.com/7717669/160121213-b8d0d434-c93c-46f6-8732-43dd17eaadc3.png">

В конфиге webpack у меня:
```
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'public/dist'),
    filename: 'bundle.js',
    clean: true
  }
  //...
}
```
Если сделать такие нехитрые изменения, то dev server начнет работать, но сломается Production сборка.
<img width="945" alt="image" src="https://user-images.githubusercontent.com/7717669/160122439-3a1fbe2c-18b1-4a6a-b37d-50648fb7d70f.png">

Благодаря изменению `path: path.resolve(__dirname, 'public')`, дев сервер теперь запускается в правильной папке public,  а не public/dist и успешно находит index.html (правда в нем не работает live reload, но это исправится изменением entry далнее)

Далее меняем entry на `entry: './src/index.html'` (т.е. не .js, а .html),  live-reload изменений в HTML начинает работать, но отваливаются стили, так как они подключены через JS, а не через HTML. А как подключить их через HTML, если я не знаю какой хеш будет сгенерирован у этих стилей? Пробую просто подключить стили прямо в html `<link rel="stylesheet" href="../assets/styles/main.css">`. Запускаю dev-server и "ура", оно работает. И live-reload и стили.. все прекрасно... Но если теперь запустить сборку для production, то вылетает ошибка:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/7717669/160123177-a84cca3b-9e4d-46a6-99e9-306eee4e8952.png">

Полный вывод:
```
(base) ivanartamonov@MacBook-Pro-Ivan:~/WebProjects/js-basic/weather$ npm run build

> weather@1.0.0 build
> webpack --node-env production

assets by status 8.09 KiB [cached] 4 assets
Entrypoint main = main.css bundle.js 3 auxiliary assets
runtime modules 3.15 KiB 10 modules
orphan modules 3.56 KiB [orphan] 3 modules
cacheable modules 1.32 KiB (javascript) 50 bytes (asset) 35 bytes (css/mini-extract)
  javascript modules 1.27 KiB
    ./src/index.html 775 bytes [built] [code generated]
    ./node_modules/html-loader/dist/runtime/getUrl.js 530 bytes [built] [code generated]
  modules by path ./assets/styles/*.css 42 bytes (javascript) 50 bytes (asset) 35 bytes (css/mini-extract)
    ./assets/styles/main.css 42 bytes (javascript) 50 bytes (asset) [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./assets/styles/main.css 35 bytes [built] [code generated]

ERROR in b88d04fba731603756b1.css
b88d04fba731603756b1.css from Css Minimizer plugin
Error: Unexpected '/'. Escaping special characters with \ may help.
    at /Users/ivanartamonov/WebProjects/js-basic/weather/b88d04fba731603756b1.css:1:1
    at Root._error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:174:16)
    at Root.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:740:21)
    at Parser.unexpected (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:758:17)
    at Parser.combinator (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:656:12)
    at Parser.parse (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1101:14)
    at Parser.loop (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
    at new Parser (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:164:10)
    at Processor._root (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:53:18)
    at Processor._runSync (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:100:21)

ERROR in   Error: Child compilation failed:
  b88d04fba731603756b1.css from Css Minimizer plugin
  Error: Unexpected '/'. Escaping special characters with \ may help.
      at /Users/ivanartamonov/WebProjects/js-basic/weather/b88d04fba731603756b1.css:1:1
      at Root._error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:174:16)
      at Root.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
      at Parser.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:740:21)
      at Parser.unexpected (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:758:17)
      at Parser.combinator (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:656:12)
      at Parser.parse (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1101:14)
      at Parser.loop (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
      at new Parser (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:164:10)
      at Processor._root (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:53:18)
      at Processor._runSync (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:100:21)
  Error: b88d04fba731603756b1.css from Css Minimizer plugin
  Error: Unexpected '/'. Escaping special characters with \ may help.
      at /Users/ivanartamonov/WebProjects/js-basic/weather/b88d04fba731603756b1.css:1:1
      at Root._error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:174:16)
      at Root.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
      at Parser.error (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:740:21)
      at Parser.unexpected (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:758:17)
      at Parser.combinator (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:656:12)
      at Parser.parse (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1101:14)
      at Parser.loop (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
      at new Parser (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/parser.js:164:10)
      at Processor._root (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:53:18)
      at Processor._runSync (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/postcss-selector-parser/dist/processor.js:100:21)
      at Function.buildError (/Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/css-minimizer-webpack-plugin/dist/index.js:354:20)
      at /Users/ivanartamonov/WebProjects/js-basic/weather/node_modules/css-minimizer-webpack-plugin/dist/index.js:544:32
  
  - b88d04fba731603756b1.css:1 
    /Users/ivanartamonov/WebProjects/js-basic/weather/b88d04fba731603756b1.css:1:1
  
  - parser.js:174 Root._error
    [weather]/[postcss-selector-parser]/dist/parser.js:174:16
  
  - root.js:43 Root.error
    [weather]/[postcss-selector-parser]/dist/selectors/root.js:43:19
  
  - parser.js:740 Parser.error
    [weather]/[postcss-selector-parser]/dist/parser.js:740:21
  
  - parser.js:758 Parser.unexpected
    [weather]/[postcss-selector-parser]/dist/parser.js:758:17
  
  - parser.js:656 Parser.combinator
    [weather]/[postcss-selector-parser]/dist/parser.js:656:12
  
  - parser.js:1101 Parser.parse
    [weather]/[postcss-selector-parser]/dist/parser.js:1101:14
  
  - parser.js:1043 Parser.loop
    [weather]/[postcss-selector-parser]/dist/parser.js:1043:12
  
  - parser.js:164 new Parser
    [weather]/[postcss-selector-parser]/dist/parser.js:164:10
  
  - processor.js:53 Processor._root
    [weather]/[postcss-selector-parser]/dist/processor.js:53:18
  
  - processor.js:100 Processor._runSync
    [weather]/[postcss-selector-parser]/dist/processor.js:100:21
  
  - Error: b88d04fba731603756b1.css from Css Minimizer plugin
  
  - Error: Unexpected '/'. Escaping special characters with \ may help.
  
  - b88d04fba731603756b1.css:1 
    /Users/ivanartamonov/WebProjects/js-basic/weather/b88d04fba731603756b1.css:1:1
  
  - parser.js:174 Root._error
    [weather]/[postcss-selector-parser]/dist/parser.js:174:16
  
  - root.js:43 Root.error
    [weather]/[postcss-selector-parser]/dist/selectors/root.js:43:19
  
  - parser.js:740 Parser.error
    [weather]/[postcss-selector-parser]/dist/parser.js:740:21
  
  - parser.js:758 Parser.unexpected
    [weather]/[postcss-selector-parser]/dist/parser.js:758:17
  
  - parser.js:656 Parser.combinator
    [weather]/[postcss-selector-parser]/dist/parser.js:656:12
  
  - parser.js:1101 Parser.parse
    [weather]/[postcss-selector-parser]/dist/parser.js:1101:14
  
  - parser.js:1043 Parser.loop
    [weather]/[postcss-selector-parser]/dist/parser.js:1043:12
  
  - parser.js:164 new Parser
    [weather]/[postcss-selector-parser]/dist/parser.js:164:10
  
  - processor.js:53 Processor._root
    [weather]/[postcss-selector-parser]/dist/processor.js:53:18
  
  - processor.js:100 Processor._runSync
    [weather]/[postcss-selector-parser]/dist/processor.js:100:21
  
  - index.js:354 Function.buildError
    [weather]/[css-minimizer-webpack-plugin]/dist/index.js:354:20
  
  - index.js:544 
    [weather]/[css-minimizer-webpack-plugin]/dist/index.js:544:32
  
  - child-compiler.js:169 
    [weather]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:564 
    [weather]/[webpack]/lib/Compiler.js:564:11
  
  - Compiler.js:1183 
    [weather]/[webpack]/lib/Compiler.js:1183:17
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [weather]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1179 
    [weather]/[webpack]/lib/Compiler.js:1179:33
  
  - Compilation.js:2786 finalCallback
    [weather]/[webpack]/lib/Compilation.js:2786:11
  
  - Compilation.js:3091 
    [weather]/[webpack]/lib/Compilation.js:3091:11
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [weather]/[tapable]/lib/Hook.js:18:14
  


1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.70.0 compiled with 3 errors in 2336 ms
```

По ошибке понял, что проблема возникает на этапе применения CssMinimizerPlugin, если его отключить, то сборка проходит без проблем, но стили, понятное дело, не минифицируются, что не годится. Гугление ошибки `ERROR in child compilations` намекает, что есть какая-то ошибка в настройке HtmlLoader и том, что он просто переносит файлы с помощью FileLoader или что-то такое... В этот момент я понял, что запутался окончательно и сдался...

В этом [коммите](https://github.com/ivanartamonov/otus-weather/commit/4653213af2367a928bc20252286dc1b09a8bc707) настроил, чтоб работал dev-server, но пришлось отключить CssMinimizerPlugin, чтоб работала сборка production... 

**Конкретный вопрос:**
Как же все-таки настроить сборку и webpack dev-server так, чтоб он корректно работал со структурой вида "public/dist", описанной выше?

**Почему вообще я сделал такую структуру директорий?**
Самое простое решение - отказаться от этой структуры и все будет работать. Но у меня в голове тогда возникает следующая проблема:
- Содержимое папки dist генерируется автоматически, очищается каждый раз и не хранится в репозитории
- А как быть со всякими файликами вида robots.txt, sitemap.xml, yandex-verification.html, ads.txt и прочим необходимым мусором, который всегда есть в любом реальном проекте? Мне его хранить в какой-то другой папке и webpack будет это переносить в dist? Мне показалось это некрасивым решением...

**Comment by AntiHero** [comment]
1. ты можешь создать папку dist и хранить в ней нужные тебе файлы, webpack их не будет удалять, а с `clean: true` удаляются только те ассеты, с которыми он работает
2. > Получается, что dev-server запущен как бы в папке "public/dist", а должен работать из "public". 

Не должен, dev-server работает  с той директорией, которая указана в `path`, это корневая директория, если не задан `publiPath`, а index.html он найти не может, потому что он на уровень выше, поэтому и сработало у тебя изменения `path` с public/dist на `public`.
 
Ты эту проблему можешь решить в другую сторону, сделать `path` c public, а все ассеты перенести в dist, т.е. в случае с js у тебя `filename` будет, например `dist/bundle.js` и т.д.

Чтобы у тебя работал hot reload добавляешь в конфиг объект dev server'a `hot: true` и `watchFiles: ["./src/*"]`, watch Files как раз и позволяет следить за изменениями нужных тебе файлов, в том числе и html

P.S я не думаю, что задавать `entrypoint` как .html было хорошей идеей

**Comment by ivanartamonov** [comment]
Спасибо за помощь :)

Все сработало, кроме одного: `clean: true` таки очищает всю папку, а не только те файлы, с которыми работает. Так как у меня сейчас dev-server смотрит в корневую директорию и clean: true, то он ее каждый раз очищает и я не могу там сохранить какой-нибудь условный robots.txt, он удаляется... 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/7717669/160207693-451e8813-ba2e-4665-87b5-184b5989f611.png">

Вся папка public будет очищена...

Изменения в конфиге, чтоб вам не ходить далеко в коммит... ну и [коммит](https://github.com/ivanartamonov/otus-weather/commit/05d468392575a8e2766206d3b5783ef8293900d3), если вдруг захочется.
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/7717669/160207478-b7ed8dc6-b1e9-44ab-a283-38b680bee9f7.png">

Я видел в документации, что в clean можно передавать функцию и делать там любую логику, какую хочешь, типа

```
module.exports = {
  //...
  output: {
    clean: {
      keep(asset) {
        return asset.includes('ignored/dir');
      },
    },
  },
};
```

но кажется это какое-то извращение для задачи "не удалять robots.txt и другие подобные файлы из корня". У меня ощущение, что либо этой проблемы вообще не существует, потому что обычно все делают как-то по-другому, либо она решается как-то кардинально иначе. Я уверен, что никто не прописывает такие файлы в функции clean, как список исключений. Можете подсказать, может как у вас на вашем текущем или каких-то прошлых проектах?

P.S. Для ДЗ наверно мне не нужен никакой robots.txt и можно было бы забить, но для реального проекта на будущее все-таки хочется разобраться 🤔

**Comment by AntiHero** [comment]
как вариант можно добавить в исключения нужные тебе файлы и таким способом, который ты описал, почему это извращение? второй способ, взять, например, какой-нибудь CopyWebpackPlugin, который из отдельной папки, в которой лежит всё это остальное добро: 'robots.txt', 'favicon.ico' и т.д. в отдельную папку, и копировать с этим плагином все файлы из этой папки в твой /dist
https://webpack.js.org/plugins/copy-webpack-plugin/

**Comment by ivanartamonov** [comment]
Сделал с помощью copy-webpack-plugin, спасибо 👌

[коммит](https://github.com/ivanartamonov/otus-weather/commit/df169a9009eb15a92a6559924a300d8a2050e17d)
